#top level makefile
#
# 2024-05-11
# Adrian Tomczyk
# adrian.tk@gmail.com
#
# it is divided for many nested include files for maintance
# if You like to use one make file, just copy contents of include files
# in place of include definition


# files to compile
# separate with blanks if more that one
SRCS = flag_timing_blink.c

# if needed set fuse here
# might be programed with "make fuse_set"
#
# 8 MHz
#L_FUSE = 0xe4
#H_FUSE = 0xd9

include ../attiny412_makefile
